' Timer_2 example activity diagram 

@startuml

skinparam sequence {
ArrowColor #009944
ActorBorderColor #009944
LifeLineBorderColor #009944
LifeLineBackgroundColor #00AA55
ParticipantBorderColor #009944
ParticipantBackgroundColor #00AA55
}

actor Usuari order 1
participant GPIO_ISR order 2
participant Timer order 3
participant LED order 4
|||
Usuari -> GPIO_ISR: Botó
GPIO_ISR  -->> Timer: Start
... 1 segon...
Timer -->> LED: Toggle


@enduml
